version: '3.7'

services:
  pagantis-app:
    build:
      context: server/pagantis-pagacoin-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker" 
    restart: always
    networks:
      - pagantis-backend
      - pagantis-frontend
    depends_on: 
      - mysqldb
  
  react-front:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        REACT_APP_URL: http://127.0.0.1:8080/api/
    ports:
      - '3000:80'
    networks:
      - pagantis-frontend
    depends_on:
      - pagantis-app

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db_pagantis
    networks:
      - pagantis-backend  

networks:
  pagantis-backend:
  pagantis-frontend: