version: '3.7'

services:
  pagantis-app:
    build:
      context: server/pagantis-pagacoin-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker" 
    restart: always
    networks:
      - pagantis-backend
    depends_on: 
      - mysqldb

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db_pagantis
    networks:
      - pagantis-backend  

networks:
  pagantis-backend: